### ISSUE TITLE
Problema de traducción

### ISSUE THREAD

**Issue by nicotron** [disenoudd/La-Naturaleza-del-Codigo#11]
Estoy en la sección I.3 y dentro del texto, cuando Dan explica como funcionan las probabilidades dice:
> …the probability of the occurrence of a given event equals the number of outcomes that qualify as that event divided by the total number of all possible outcomes.

Y yo lo tengo hasta ahora traducido:

> la probabilidad de que un evento dado ocurra es igual al número de resultados que califican como ese evento dividido por el número total de todos los posibles resultados. 

No estoy seguro de que el texto en español sea entendible.

**Comment by sergiomajluf** [comment]
Me parece que hace sentido. Sobre todo con el ejemplo de cara y sello que viene a continuación. Quizás sólo le agregaría una coma:

> la probabilidad de que un evento dado ocurra es igual al número de resultados que califican como ese evento, dividido por el número total de todos los posibles resultados.

En inglés esa coma no va, porque se puede invertir el orden de las palabras para dar a entender por ejemplo diciendo "that qualify as that divided event". En español, la coma evita que tengamos esa confusión
