### ISSUE TITLE
Estructura de notación para el libro

### ISSUE THREAD

**Issue by nicotron** [disenoudd/La-Naturaleza-del-Codigo#6]
Hola a todos. 
Estoy haciendo este **issue** para que aprendamos como esta herramienta puede ayudarnos en la coordinación a lo largo del libro y también para ver un tema en particular. 

### La estructura de la notación.
En la barra de menú que está entre el título del repositorio y este issue, existe una herramienta que se llama **Wiki** y es perfecto para que contenga la información de notación a medida que aparezcan palabras claves cómo **Walker** a lo largo del libro. 

Acá entonces podemos discutir este issue en particular, si existe alguna otra duda que no podamos discutir los jueves, puede ser ingresada como otro issue y asignada a quién encuentren necesario, por ejemplo en este caso asigné la duda de este issue a @sergiomajluf. (se asigna en la barra lateral dentro de la página)

**Comment by sergiomajluf** [comment]
Para resolver el tema de la traducción, creé [un glosario](https://github.com/disenoudd/La-Naturaleza-del-Codigo/wiki/Glosario) en el wiki. En ese glosario podemos mantener dos listados, el primero con palabras sin traducción definida, y el segundo, con la traducción que acordemos entre todos.
