### ISSUE TITLE
Notación de tildes en la escritura del libro

### ISSUE THREAD

**Issue by palosastre** [disenoudd/La-Naturaleza-del-Codigo#7]
Muchas de las palabras que usaremos al traducir el libro, utilizan tildes. El super koopa troopa (Schiffman), usó `we&rsquo;ll` cuando se quería referir a **"we'll"**. Nosotros, ¿cómo lo haremos? No tengo entendido si funciona poner tildes en el código.

**Comment by nicotron** [comment]
Una opción es que todos escribamos con tildes y una vez que tengamos que actualizar los archivos html vayamos a esta referencia y usando la herramienta **find and replace** reemplacemos los tildes `áéíóú` por `&aacute;` en donde la letra siguiente al `&` es la letra tildada. 
También podemos crear en el glosario un espacio con cada uno de estos códigos. c`&oacute`digos

**Comment by nicotron** [comment]
Creo que lo mejor es que cada uno cambie la notación de cada tilde cuando corresponda ya que es parte del proceso de traducción para formatos digitales.

**Comment by sergiomajluf** [comment]
Hola!

perdón por la tardanza en contestar. En la prueba que tienes corriendo de MagicBook, los acentos y caracteres especiales generan algún tipo de problemas?

Podrías probar rendereando un html que tenga tanto áéíóúñ como &aacute; &eacute; &iacute; &oacute; &uacute; &ntilde; ?

**Comment by nicotron** [comment]
Hice una prueba con magicbook leyendo tildes y signos de interrogación en archivos md y html, con la frase ¿Cuándo será el día de la canción feliz? dando como resultado la transformación de esos signos a formato html sin problemas de lectura. 
Así que es posible escribir con tildes y signos sin problemas durante todo el texto
